runtime: custom
env: flex

service: test-app
resources:
  cpu: 1
  memory_gb: 1

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.5
