version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.15.1
jobs:
  build-and-push:
    - gcp-gcr/build-and-push-image:
        context: myContext
        executor: my-executor
        image: my-first-container:${CIRCLE_SHA1}
        use-docker-layer-caching: true
workflows:
  build-and-deploy:
    jobs:
      - build-and-push
