version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.15.1
workflows:
  build_and_push_image:
    jobs:
      - gcp-gcr/build-and-push-image:
          image: my-image
          setup-remote-docker: true
          use-docker-layer-caching: true