version: 2.1

jobs:
  build:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push Docker image
          command: |
            docker build -t ${DOCKER_USERNAME}/my-first-container:${CIRCLE_SHA1} .
            docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
            docker push ${DOCKER_USERNAME}/my-first-container:${CIRCLE_SHA1}

  deploy:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - run:
          name: Authenticating and configuring the Google Cloud Platform
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - run:
          name: Deploy docker image to app engine
          command: |
            gcloud app deploy ../app.yaml --image-url=docker.io/${DOCKER_USERNAME}/my-first-container:${CIRCLE_SHA1} --quiet --version=${CIRCLE_SHA1}
workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
