version: 2.1

jobs:
  build:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push Docker image
          command: |
            docker build -t prabhugurung/my-first-container:${CIRCLE_SHA1} .
            docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
            docker push username/my-app:${CIRCLE_SHA1}

      - run:
          name: Deploy docker image to app engine
          command: |
            gcloud app deploy --image-url=docker.io/${DOCKER_USERNAME}/my-first-container:${CIRCLE_SHA1} --quiet --version=${CIRCLE_SHA1}

workflows:
  build-and-deploy:
    jobs:
      - build:
          context: docker-context
